name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Robot berjalan otomatis setiap kali Anda push ke branch main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project Vue
        run: npm run build

      - name: Deploy to GitHub Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Folder hasil kompresi 'npm run build' yang akan dikirim ke branch gh-pages
          branch: gh-pages